// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5z3SULiGaaCzgRp7mpyYO_G8HgGA72s',
    appId: '1:969925467000:android:80c50e25860038bf61868d',
    messagingSenderId: '969925467000',
    projectId: 'notdefrt',
    storageBucket: 'notdefrt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOl7JRuqCBz8hLERUSBr1R2-0dCgIkKaw',
    appId: '1:969925467000:ios:73571617906c7efa61868d',
    messagingSenderId: '969925467000',
    projectId: 'notdefrt',
    storageBucket: 'notdefrt.firebasestorage.app',
    iosBundleId: 'com.notdefterim.notDefterim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU2FWIHRugDEkSJ7mRoapYCvW5oVZJQYY',
    appId: '1:969925467000:web:ed3183948630d5c161868d',
    messagingSenderId: '969925467000',
    projectId: 'notdefrt',
    authDomain: 'notdefrt.firebaseapp.com',
    storageBucket: 'notdefrt.firebasestorage.app',
    measurementId: 'G-W4CF4TW9T7',
  );
}
